/*
 * All-time standings carried over from the parent league, frozen at the
 * point of the fork (2026-08-16). This is a one-time snapshot, not a live
 * derivation — nothing here recomputes from the ledger. `slug` points at
 * the team's roster page and is stable across renames, same as everywhere
 * else team links are built.
 */
export type LegacyStanding = {
  team: string;
  slug: string;
  wins: number;
  losses: number;
  winPct: string;
  pointsScored: string;
  pointsAgainst: string;
  highestScorerSeasons: number | null;
  playoffAppearances: number | null;
  playoffRecord: string | null;
  oneSeedAppearances: number | null;
  titleAppearances: number | null;
  titleWins: number | null;
  bpotya: number | null;
  coty: number | null;
};

export const legacyStandings: LegacyStanding[] = [
  {
    team: "Ludda",
    slug: "buuls",
    wins: 10,
    losses: 4,
    winPct: "71.00%",
    pointsScored: "1,901.27",
    pointsAgainst: "1,519.24",
    highestScorerSeasons: null,
    playoffAppearances: 1,
    playoffRecord: "2-0",
    oneSeedAppearances: null,
    titleAppearances: 1,
    titleWins: 1,
    bpotya: null,
    coty: null,
  },
  {
    team: "Wyatt W",
    slug: "puglover",
    wins: 9,
    losses: 5,
    winPct: "64.00%",
    pointsScored: "2,065.43",
    pointsAgainst: "1,733.04",
    highestScorerSeasons: 1,
    playoffAppearances: 1,
    playoffRecord: "2-1",
    oneSeedAppearances: null,
    titleAppearances: 1,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Will T",
    slug: "pigskin",
    wins: 11,
    losses: 3,
    winPct: "78.00%",
    pointsScored: "1,978.95",
    pointsAgainst: "1,557.07",
    highestScorerSeasons: null,
    playoffAppearances: 1,
    playoffRecord: "0-1",
    oneSeedAppearances: 1,
    titleAppearances: null,
    titleWins: null,
    bpotya: 1,
    coty: 1,
  },
  {
    team: "Trey O",
    slug: "albuquerque-birky-bags",
    wins: 10,
    losses: 4,
    winPct: "71.00%",
    pointsScored: "1,786.38",
    pointsAgainst: "1,548.86",
    highestScorerSeasons: null,
    playoffAppearances: 1,
    playoffRecord: "1-1",
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Xavier B",
    slug: "freako-nico",
    wins: 10,
    losses: 4,
    winPct: "71.00%",
    pointsScored: "1,825.98",
    pointsAgainst: "1,731.34",
    highestScorerSeasons: null,
    playoffAppearances: 1,
    playoffRecord: "0-1",
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Rob T",
    slug: "didnt-ceedee-ref",
    wins: 9,
    losses: 5,
    winPct: "64.00%",
    pointsScored: "1,829.60",
    pointsAgainst: "1,632.61",
    highestScorerSeasons: null,
    playoffAppearances: 1,
    playoffRecord: "0-1",
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Marco",
    slug: "adolf-swiftler",
    wins: 8,
    losses: 6,
    winPct: "57.00%",
    pointsScored: "1,732.26",
    pointsAgainst: "1,689.55",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Robby O",
    slug: "bukkak-boys",
    wins: 8,
    losses: 6,
    winPct: "57.00%",
    pointsScored: "1,654.49",
    pointsAgainst: "1,689.17",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Qasim",
    slug: "tuten-w-qas",
    wins: 7,
    losses: 7,
    winPct: "50.00%",
    pointsScored: "1,636.14",
    pointsAgainst: "1,604.25",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Dalton B",
    slug: "wandalt",
    wins: 6,
    losses: 8,
    winPct: "43.00%",
    pointsScored: "1,702.42",
    pointsAgainst: "1,655.42",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Leif W",
    slug: "saquans-dirty-slutz",
    wins: 6,
    losses: 8,
    winPct: "43.00%",
    pointsScored: "1,502.68",
    pointsAgainst: "1,597.13",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Diego M",
    slug: "troys-boys",
    wins: 4,
    losses: 10,
    winPct: "29.00%",
    pointsScored: "1,398.77",
    pointsAgainst: "1,831.13",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Lucca K",
    slug: "lucca-x-griff",
    wins: 4,
    losses: 10,
    winPct: "29.00%",
    pointsScored: "1,405.62",
    pointsAgainst: "1,724.23",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Dylan F",
    slug: "fluther-burden-iii",
    wins: 4,
    losses: 10,
    winPct: "29.00%",
    pointsScored: "1,397.16",
    pointsAgainst: "1,674.53",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Adrian D and Evan",
    slug: "daddydteam",
    wins: 3,
    losses: 11,
    winPct: "21.00%",
    pointsScored: "1,348.25",
    pointsAgainst: "1,765.22",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
  {
    team: "Griffen",
    slug: "lucca-x-griff",
    wins: 3,
    losses: 11,
    winPct: "21.00%",
    pointsScored: "1,389.78",
    pointsAgainst: "1,602.41",
    highestScorerSeasons: null,
    playoffAppearances: null,
    playoffRecord: null,
    oneSeedAppearances: null,
    titleAppearances: null,
    titleWins: null,
    bpotya: null,
    coty: null,
  },
];
